model_name_or_path: Qwen/Qwen2.5-3B-Instruct
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 4
lora_alpha: 8
lora_target: all
lora_dropout: 0.05
dataset: gsm8k_3b_sft_normal
dataset_dir: /common/users/sl2148/Public/yang_ouyang/projects/LostInTheSecond/LlamaFactory/data
template: qwen
cutoff_len: 2048
preprocessing_num_workers: 4
dataloader_num_workers: 2
output_dir: /common/users/sl2148/Public/yang_ouyang/projects/LostInTheSecond/results/sft_sweep/normal_lr1e-6_r4_ep10
logging_steps: 50
save_steps: 99999
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true
save_only_model: true
report_to: none
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-6
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
val_size: 0.05
per_device_eval_batch_size: 2
eval_strategy: epoch
