#!/usr/bin/env python3
"""
Build a "wait + recompute" prefill dataset from GPT-corrected GSM8K samples.

For each sample where prefill_recomputed_exact_match == 1, construct:
  pos = [step1, old_step2, "Wait, the previous step is wrong. Let's recompute.",
         corrected_step2, <model-generated tail>]

The tail is generated by the base model (Qwen2.5-3B-Instruct) continuing from
the wait+recompute prefix.

Input:  artifacts_real/samples_gsm8k_train_ds2_fix_step2_gpt_prefill.json
Output: artifacts_real/samples_gsm8k_train_ds2_wait_recompute_gpt_prefill.json
"""

import argparse
import json
import os
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

try:
    from tqdm import tqdm
except ImportError:
    tqdm = None


STEP_RE = re.compile(r"(?:^|\n)\s*Step\s*\d+\s*:\s*", re.IGNORECASE)
REPAIR_PREFIX = "Wait, the previous step is wrong. Let's recompute."

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="Build wait+recompute prefill dataset"
    )
    ap.add_argument(
        "--in-file",
        default=str(
            PROJECT_ROOT
            / "artifacts_real"
            / "samples_gsm8k_train_ds2_fix_step2_gpt_prefill.json"
        ),
    )
    ap.add_argument(
        "--out-file",
        default=str(
            PROJECT_ROOT
            / "artifacts_real"
            / "samples_gsm8k_train_ds2_wait_recompute_gpt_prefill.json"
        ),
    )
    ap.add_argument(
        "--ref-file",
        default=str(
            PROJECT_ROOT
            / "lm-evaluation-harness"
            / "math_eval_data"
            / "gsm8k_openai_main"
            / "train.jsonl"
        ),
        help="GSM8K reference for answer checking",
    )
    ap.add_argument("--model-id", default="Qwen/Qwen2.5-3B-Instruct")
    ap.add_argument("--dtype", default="float16", choices=["float16", "bfloat16"])
    ap.add_argument("--max-new-tokens", type=int, default=768)
    ap.add_argument("--temperature", type=float, default=0.7)
    ap.add_argument("--top-p", type=float, default=0.9)
    ap.add_argument("--max-attempts", type=int, default=5)
    ap.add_argument("--limit", type=int, default=0, help="0 = all")
    return ap.parse_args()


# ── helpers ──────────────────────────────────────────────────────────

def split_steps(text: str) -> List[str]:
    text = (text or "").strip()
    if not text:
        return []
    if "\n\n" in text:
        parts = [x.strip() for x in text.split("\n\n") if x.strip()]
        if len(parts) >= 2:
            return parts
    hits = list(STEP_RE.finditer(text))
    if hits:
        out = []
        for i, m in enumerate(hits):
            st = m.start()
            ed = hits[i + 1].start() if i + 1 < len(hits) else len(text)
            out.append(text[st:ed].strip())
        return [x for x in out if x]
    return [x.strip() for x in text.split("\n") if x.strip()]


def normalize_answer(text: str) -> str:
    text = (text or "").strip()
    text = text.replace("$", "").replace(",", "")
    text = re.sub(r"\\boxed\{(.*)\}", r"\1", text)
    text = re.sub(r"\\left|\\right", "", text)
    text = re.sub(r"\s+", "", text)
    return text


def extract_gsm8k_answer(text: str) -> str:
    """Extract answer from #### format (GSM8K reference) or \\boxed{} (model)."""
    m = re.search(r"####\s*(.+)", text or "")
    if m:
        return m.group(1).strip()
    idx = (text or "").rfind("\\boxed")
    if idx >= 0:
        i = idx
        num_left = 0
        right_idx = None
        while i < len(text):
            if text[i] == "{":
                num_left += 1
            if text[i] == "}":
                num_left -= 1
                if num_left == 0:
                    right_idx = i
                    break
            i += 1
        if right_idx is not None:
            inner = text[idx:right_idx + 1]
            if inner.startswith("\\boxed{") and inner.endswith("}"):
                return inner[len("\\boxed{"):-1].strip()
    m2 = re.search(r"Final Answer\s*:\s*(.*)", text or "", re.IGNORECASE)
    if m2:
        return m2.group(1).strip()
    return ""


def load_ref_answers(path: Path) -> Dict[str, str]:
    """Load GSM8K reference answers keyed by normalized question."""
    out: Dict[str, str] = {}
    if not path.exists():
        return out
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            q = re.sub(r"\s+", " ", (row.get("problem") or "").strip().lower())
            sol = row.get("solution", "")
            ans = extract_gsm8k_answer(sol)
            if q and ans:
                out[q] = ans
    return out


def qwen_chat_prompt(question: str) -> str:
    return (
        "<|im_start|>system\n"
        "You are Qwen, created by Alibaba Cloud. You are a helpful assistant.\n"
        "<|im_end|>\n"
        "<|im_start|>user\n"
        "Solve the following math problem. Present the final answer in the "
        "format: Final Answer: \\boxed{your_answer}.\n"
        f"Problem: {question}\n"
        "Answer:\n"
        "<|im_end|>\n"
        "<|im_start|>assistant\n"
    )


# ── main ─────────────────────────────────────────────────────────────

def main() -> None:
    args = parse_args()
    in_path = Path(args.in_file).resolve()
    out_path = Path(args.out_file).resolve()
    ref_path = Path(args.ref_file).resolve()

    if not in_path.exists():
        raise FileNotFoundError(f"Input not found: {in_path}")

    obj = json.loads(in_path.read_text(encoding="utf-8"))
    all_samples = obj["samples"] if isinstance(obj, dict) and "samples" in obj else obj

    ref_answers = load_ref_answers(ref_path)
    print(f"Loaded {len(ref_answers)} reference answers from {ref_path}")

    # filter for prefill_recomputed_exact_match == 1
    eligible = [
        s for s in all_samples
        if s.get("prefill_recomputed_exact_match") == 1
    ]
    print(f"Total samples: {len(all_samples)}, "
          f"prefill_recomputed_exact_match==1: {len(eligible)}")

    if args.limit > 0:
        eligible = eligible[: args.limit]
        print(f"Limiting to {len(eligible)} samples")

    # load model
    torch_dtype = torch.float16 if args.dtype == "float16" else torch.bfloat16
    print(f"Loading model {args.model_id} ...")
    tokenizer = AutoTokenizer.from_pretrained(
        args.model_id, trust_remote_code=True, use_fast=True
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        args.model_id,
        torch_dtype=torch_dtype,
        trust_remote_code=True,
        device_map="cuda:0" if torch.cuda.is_available() else "auto",
    ).eval()

    results = []
    changed = 0
    solved = 0
    total_attempts = 0

    it = tqdm(eligible, desc="wait-recompute", unit="s") if tqdm else eligible

    for item in it:
        doc = item.get("doc") or {}
        question = (doc.get("question") or doc.get("problem") or "").strip()
        if not question:
            results.append(item)
            continue

        neg_steps = item.get("neg_steps") or split_steps(item.get("neg_response", ""))
        if len(neg_steps) < 2:
            results.append(item)
            continue

        step1 = neg_steps[0].strip()
        old_step2 = neg_steps[1].strip()
        corrected_step2 = (item.get("corrected_step2") or "").strip()

        if not step1 or not corrected_step2:
            results.append(item)
            continue

        prefix_parts = [step1, old_step2, REPAIR_PREFIX, corrected_step2]
        prefix = "\n\n".join(p for p in prefix_parts if p)

        prompt = qwen_chat_prompt(question)
        prefill_text = prompt + prefix
        model_inputs = tokenizer(
            prefill_text, return_tensors="pt", add_special_tokens=False
        )
        model_inputs = {k: v.to(model.device) for k, v in model_inputs.items()}

        # gold answer: prefer the field already in the data, else look up ref
        gold = (item.get("prefill_recomputed_gold_answer") or "").strip()
        if not gold:
            q_norm = re.sub(r"\s+", " ", question.lower())
            gold = ref_answers.get(q_norm, "")

        best_regenerated = prefix
        best_tail = ""
        found_correct = False
        used_attempts = 0

        for attempt in range(1, args.max_attempts + 1):
            gen_kwargs = {
                "max_new_tokens": args.max_new_tokens,
                "do_sample": True,
                "pad_token_id": tokenizer.pad_token_id,
                "eos_token_id": tokenizer.eos_token_id,
                "temperature": args.temperature,
                "top_p": args.top_p,
            }
            if args.max_attempts == 1:
                gen_kwargs["do_sample"] = False
                gen_kwargs.pop("temperature", None)
                gen_kwargs.pop("top_p", None)

            with torch.inference_mode():
                outputs = model.generate(**model_inputs, **gen_kwargs)

            new_ids = outputs[0][model_inputs["input_ids"].shape[1]:]
            tail = tokenizer.decode(new_ids, skip_special_tokens=True).strip()
            regenerated = prefix if not tail else (prefix + "\n\n" + tail)
            used_attempts = attempt
            best_tail = tail
            best_regenerated = regenerated

            if gold:
                pred = extract_gsm8k_answer(regenerated)
                if pred and normalize_answer(pred) == normalize_answer(gold):
                    found_correct = True
                    break

        total_attempts += used_attempts
        if found_correct:
            solved += 1
        changed += 1

        new_item = {
            "doc": doc,
            "pos_response": best_regenerated,
            "neg_response": item.get("neg_response", ""),
            "pos_steps": split_steps(best_regenerated),
            "neg_steps": neg_steps,
            "corrected_step2": corrected_step2,
            "results": {"exact_match": 1.0},
            "wait_recompute_prefix": prefix,
            "wait_recompute_tail": best_tail,
            "wait_recompute_attempts": used_attempts,
            "wait_recompute_found_correct": found_correct,
            "wait_recompute_gold_answer": gold,
            "wait_recompute_pred_answer": extract_gsm8k_answer(best_regenerated),
        }
        results.append(new_item)

        if tqdm and hasattr(it, "set_postfix"):
            avg_att = (total_attempts / changed) if changed else 0
            it.set_postfix(
                changed=changed, solved=solved, avg_att=f"{avg_att:.2f}"
            )

    out_obj = {
        "samples": results,
        "wait_recompute_meta": {
            "input_file": str(in_path),
            "ref_file": str(ref_path),
            "model_id": args.model_id,
            "max_new_tokens": args.max_new_tokens,
            "temperature": args.temperature,
            "top_p": args.top_p,
            "max_attempts": args.max_attempts,
            "num_eligible": len(eligible),
            "num_changed": changed,
            "num_solved": solved,
            "avg_attempts": (total_attempts / changed) if changed else 0,
        },
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        json.dumps(out_obj, indent=2, ensure_ascii=False), encoding="utf-8"
    )
    print(f"\nDone. Changed={changed}, Solved={solved}/{changed}")
    print(f"Output: {out_path}")


if __name__ == "__main__":
    os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
    main()
